version: '3.3'

services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/my_backend/src
    env_file:
      - ./.env.stage
    ports:
      - 3000:3000

  my_database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myproject'
      MYSQL_ROOT_PASSWORD: 'root'
