version: "3.3"

services: 
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  my_database:
    image: mongo:latest
    ports:
      - 27017:27017