version: "3.3"

services: 
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./:/myfolder/

  my_database:
    build:
        context: .
        dockerfile: Dockerfile.mongo
    # image: mongo:latest
    ports:
      - 27017:27017