version: "3.3"

services: 
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/myfolder/

  my_database:
    image: mongo:latest
    ports:
      - 27017:27017