version: "3.3"

services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/my_backend/src
      - ./.env:/my_backend/.env
    ports:
      - 3000:3000

  my_database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "docker-database"
      MYSQL_ROOT_PASSWORD: "072865as!"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
